<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BuenasPracticasRecomendacionesSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedBuenasPracticas();
        $this->seedRecomendaciones();
    }

    private function seedBuenasPracticas(): void
    {
        // Usuarios institucionales reales (IDs 2–17)
        $usuarios  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13];
        $unidades  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

        $practicas = [
            // Enero 2026
            [
                'titulo'       => 'Implementación del archivo documentario digital',
                'descripcion'  => 'Digitalización y organización del acervo documentario institucional mediante sistema de gestión documental, reduciendo el tiempo de búsqueda de expedientes en un 70%.',
                'categoria'    => 'innovacion',
                'unidad_id'    => 2,
                'responsable'  => 3,
                'estado'       => 'completada',
                'avance'       => 100,
                'inicio'       => '2026-01-06',
                'termino'      => '2026-02-28',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-001-2026',
                'evidencias'   => 'Acta de implementación, manual de usuario, registro de capacitación al personal.',
                'creado_por'   => 1,
                'created_at'   => '2026-01-06 08:00:00',
            ],
            [
                'titulo'       => 'Programa de atención al ciudadano con cita previa',
                'descripcion'  => 'Implementación de sistema de citas previas para trámites administrativos, reduciendo tiempos de espera y mejorando la satisfacción del usuario externo.',
                'categoria'    => 'gestion',
                'unidad_id'    => 2,
                'responsable'  => 5,
                'estado'       => 'completada',
                'avance'       => 100,
                'inicio'       => '2026-01-12',
                'termino'      => '2026-03-15',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-002-2026',
                'evidencias'   => 'Registro de citas atendidas, encuesta de satisfacción, informe de resultados.',
                'creado_por'   => 1,
                'created_at'   => '2026-01-12 09:30:00',
            ],
            // Febrero 2026
            [
                'titulo'       => 'Fortalecimiento de capacidades en control interno',
                'descripcion'  => 'Programa de capacitación continua al personal en materia de Sistema de Control Interno, con talleres mensuales y evaluación de competencias.',
                'categoria'    => 'integridad',
                'unidad_id'    => 1,
                'responsable'  => 2,
                'estado'       => 'completada',
                'avance'       => 100,
                'inicio'       => '2026-02-03',
                'termino'      => '2026-04-30',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-008-2026',
                'evidencias'   => 'Lista de asistencia a talleres, evaluaciones aplicadas, certificados emitidos.',
                'creado_por'   => 2,
                'created_at'   => '2026-02-03 08:00:00',
            ],
            [
                'titulo'       => 'Portal de transparencia con información actualizada mensualmente',
                'descripcion'  => 'Actualización mensual y oportuna del portal de transparencia con información presupuestal, contratos, personal y actos administrativos conforme a la Ley N° 27806.',
                'categoria'    => 'transparencia',
                'unidad_id'    => 1,
                'responsable'  => 4,
                'estado'       => 'en_implementacion',
                'avance'       => 85,
                'inicio'       => '2026-02-10',
                'termino'      => '2026-12-31',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-012-2026',
                'evidencias'   => 'Capturas del portal, cronograma de actualización, constancia de publicación.',
                'creado_por'   => 4,
                'created_at'   => '2026-02-10 10:00:00',
            ],
            // Marzo 2026
            [
                'titulo'       => 'Optimización del proceso de viáticos y comisiones de servicio',
                'descripcion'  => 'Estandarización y simplificación del proceso de solicitud, aprobación y rendición de viáticos, reduciendo el tiempo de procesamiento de 5 a 2 días hábiles.',
                'categoria'    => 'gestion',
                'unidad_id'    => 9,
                'responsable'  => 9,
                'estado'       => 'completada',
                'avance'       => 100,
                'inicio'       => '2026-03-02',
                'termino'      => '2026-04-15',
                'impacto'      => 'medio',
                'sgd'          => 'SGD-018-2026',
                'evidencias'   => 'Nuevo flujograma aprobado, directiva interna, registro de tiempos antes/después.',
                'creado_por'   => 9,
                'created_at'   => '2026-03-02 08:30:00',
            ],
            [
                'titulo'       => 'Plan de gestión de riesgos de corrupción',
                'descripcion'  => 'Elaboración e implementación del plan de gestión de riesgos de corrupción identificando 12 procesos críticos y estableciendo controles preventivos en cada uno.',
                'categoria'    => 'integridad',
                'unidad_id'    => 5,
                'responsable'  => 6,
                'estado'       => 'completada',
                'avance'       => 100,
                'inicio'       => '2026-03-09',
                'termino'      => '2026-05-30',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-021-2026',
                'evidencias'   => 'Matriz de riesgos aprobada, plan de gestión, actas de socialización con unidades.',
                'creado_por'   => 6,
                'created_at'   => '2026-03-09 09:00:00',
            ],
            // Abril 2026
            [
                'titulo'       => 'Banco de recursos pedagógicos para docentes rurales',
                'descripcion'  => 'Creación de repositorio digital de materiales educativos contextualizados para instituciones educativas de zonas rurales de la provincia de Huacaybamba.',
                'categoria'    => 'innovacion',
                'unidad_id'    => 3,
                'responsable'  => 7,
                'estado'       => 'en_implementacion',
                'avance'       => 70,
                'inicio'       => '2026-04-06',
                'termino'      => '2026-07-31',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-031-2026',
                'evidencias'   => 'Plataforma digital habilitada, 45 materiales cargados, 120 docentes registrados.',
                'creado_por'   => 7,
                'created_at'   => '2026-04-06 08:00:00',
            ],
            [
                'titulo'       => 'Mesa de partes virtual para trámites documentarios',
                'descripcion'  => 'Habilitación de mesa de partes virtual que permite el ingreso de documentos en línea, reduciendo el desplazamiento de ciudadanos a la sede institucional.',
                'categoria'    => 'transparencia',
                'unidad_id'    => 2,
                'responsable'  => 8,
                'estado'       => 'en_implementacion',
                'avance'       => 60,
                'inicio'       => '2026-04-13',
                'termino'      => '2026-08-31',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-035-2026',
                'evidencias'   => 'Mesa de partes virtual operativa, manual de usuario publicado, 85 trámites recibidos.',
                'creado_por'   => 8,
                'created_at'   => '2026-04-13 09:30:00',
            ],
            // Mayo 2026
            [
                'titulo'       => 'Programa de acompañamiento pedagógico en matemáticas',
                'descripcion'  => 'Implementación de programa de acompañamiento docente especializado en matemáticas para II.EE. con bajo rendimiento en ECE, con visitas quincenales.',
                'categoria'    => 'gestion',
                'unidad_id'    => 3,
                'responsable'  => 10,
                'estado'       => 'en_implementacion',
                'avance'       => 55,
                'inicio'       => '2026-05-04',
                'termino'      => '2026-11-30',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-045-2026',
                'evidencias'   => '12 II.EE. focalizadas, 24 visitas realizadas, informes de acompañamiento.',
                'creado_por'   => 10,
                'created_at'   => '2026-05-04 08:00:00',
            ],
            [
                'titulo'       => 'Inventario patrimonial con código de barras',
                'descripcion'  => 'Modernización del control patrimonial mediante etiquetado con código de barras de todos los bienes institucionales y sistema de escaneo para registros rápidos.',
                'categoria'    => 'gestion',
                'unidad_id'    => 7,
                'responsable'  => 11,
                'estado'       => 'en_implementacion',
                'avance'       => 45,
                'inicio'       => '2026-05-11',
                'termino'      => '2026-09-30',
                'impacto'      => 'medio',
                'sgd'          => 'SGD-052-2026',
                'evidencias'   => '340 bienes etiquetados de 756 totales, base de datos actualizada.',
                'creado_por'   => 11,
                'created_at'   => '2026-05-11 09:00:00',
            ],
            // Junio 2026
            [
                'titulo'       => 'Protocolo de atención a denuncias ciudadanas',
                'descripcion'  => 'Diseño e implementación de protocolo estandarizado para la recepción, registro, derivación y seguimiento de denuncias ciudadanas, garantizando respuesta en máximo 15 días.',
                'categoria'    => 'transparencia',
                'unidad_id'    => 5,
                'responsable'  => 12,
                'estado'       => 'en_implementacion',
                'avance'       => 40,
                'inicio'       => '2026-06-01',
                'termino'      => '2026-09-30',
                'impacto'      => 'medio',
                'sgd'          => 'SGD-058-2026',
                'evidencias'   => 'Protocolo aprobado mediante Resolución Directoral, formato de registro implementado.',
                'creado_por'   => 12,
                'created_at'   => '2026-06-01 08:00:00',
            ],
            [
                'titulo'       => 'Comité de ética y buen gobierno institucional',
                'descripcion'  => 'Conformación y activación del Comité de Ética Institucional con reuniones mensuales, seguimiento a compromisos de integridad y difusión del Código de Ética.',
                'categoria'    => 'integridad',
                'unidad_id'    => 1,
                'responsable'  => 2,
                'estado'       => 'pendiente',
                'avance'       => 15,
                'inicio'       => '2026-06-09',
                'termino'      => '2026-12-31',
                'impacto'      => 'medio',
                'sgd'          => 'SGD-063-2026',
                'evidencias'   => null,
                'creado_por'   => 1,
                'created_at'   => '2026-06-09 09:00:00',
            ],
            [
                'titulo'       => 'Sistema de indicadores de gestión por unidad orgánica',
                'descripcion'  => 'Diseño e implementación de tablero de indicadores de desempeño por unidad orgánica, con metas mensuales y reportes automáticos para la Dirección.',
                'categoria'    => 'gestion',
                'unidad_id'    => 4,
                'responsable'  => 13,
                'estado'       => 'pendiente',
                'avance'       => 10,
                'inicio'       => '2026-06-02',
                'termino'      => '2026-10-31',
                'impacto'      => 'alto',
                'sgd'          => 'SGD-060-2026',
                'evidencias'   => null,
                'creado_por'   => 13,
                'created_at'   => '2026-06-02 08:30:00',
            ],
            [
                'titulo'       => 'Participación ciudadana en presupuesto participativo',
                'descripcion'  => 'Programa de involucramiento de comunidad educativa en la priorización de necesidades institucionales y seguimiento de inversiones.',
                'categoria'    => 'participacion',
                'unidad_id'    => 4,
                'responsable'  => 5,
                'estado'       => 'pendiente',
                'avance'       => 5,
                'inicio'       => '2026-06-07',
                'termino'      => '2026-11-30',
                'impacto'      => 'medio',
                'sgd'          => null,
                'evidencias'   => null,
                'creado_por'   => 5,
                'created_at'   => '2026-06-07 10:00:00',
            ],
        ];

        foreach ($practicas as $p) {
            DB::table('buenas_practicas')->insert([
                'titulo'             => $p['titulo'],
                'descripcion'        => $p['descripcion'],
                'categoria'          => $p['categoria'],
                'unidad_organica_id' => $p['unidad_id'],
                'responsable_id'     => $p['responsable'],
                'estado'             => $p['estado'],
                'avance'             => $p['avance'],
                'fecha_inicio'       => $p['inicio'],
                'fecha_termino'      => $p['termino'],
                'numero_sgd'         => $p['sgd'] ?? null,
                'impacto'            => $p['impacto'],
                'evidencias'         => $p['evidencias'] ?? null,
                'observaciones'      => null,
                'creado_por'         => $p['creado_por'],
                'created_at'         => $p['created_at'],
                'updated_at'         => $p['created_at'],
                'deleted_at'         => null,
            ]);
        }

        $this->command->info('✅ Buenas Prácticas: ' . count($practicas) . ' registros insertados.');
    }

    private function seedRecomendaciones(): void
    {
        $actividadesIds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 14];

        $recomendaciones = [
            // Enero 2026
            [
                'titulo'       => 'Actualizar procedimiento de rendición de cuentas de caja chica',
                'descripcion'  => 'Se identificó que el procedimiento de rendición de caja chica no ha sido actualizado desde el año 2022, no contempla los cambios normativos de la Directiva N° 005-2023-EF/43.01. Se recomienda actualizar el procedimiento en un plazo de 30 días.',
                'tipo'         => 'recomendacion',
                'actividad_id' => 4,
                'unidad_id'    => 6,
                'responsable'  => 9,
                'estado'       => 'atendida',
                'prioridad'    => 'alta',
                'emision'      => '2026-01-15',
                'limite'       => '2026-02-15',
                'atencion'     => '2026-02-10',
                'sgd'          => 'SGD-004-2026',
                'origen'       => 'OCI',
                'obs'          => 'Procedimiento actualizado mediante Resolución Directoral. Se capacitó al personal de Tesorería.',
                'creado_por'   => 1,
                'created_at'   => '2026-01-15 09:00:00',
            ],
            [
                'titulo'       => 'Regularizar contratos de locadores de servicios vencidos',
                'descripcion'  => 'Verificación detectó 8 contratos de locación de servicios con vigencia vencida al 31/12/2025 que continúan prestando servicios sin renovación formal. Riesgo legal y presupuestal.',
                'tipo'         => 'observacion',
                'actividad_id' => 5,
                'unidad_id'    => 8,
                'responsable'  => 3,
                'estado'       => 'atendida',
                'prioridad'    => 'alta',
                'emision'      => '2026-01-20',
                'limite'       => '2026-01-31',
                'atencion'     => '2026-01-28',
                'sgd'          => 'SGD-006-2026',
                'origen'       => 'Auditoría',
                'obs'          => '8 contratos renovados. Se implementó alerta en calendario para vencimientos futuros.',
                'creado_por'   => 2,
                'created_at'   => '2026-01-20 10:30:00',
            ],
            // Febrero 2026
            [
                'titulo'       => 'Implementar libro de reclamaciones en formato digital',
                'descripcion'  => 'La UGEL no cuenta con libro de reclamaciones accesible en formato digital conforme a lo dispuesto por el DS N° 042-2011-PCM. Se recomienda habilitar formulario web y QR en mesa de partes.',
                'tipo'         => 'recomendacion',
                'actividad_id' => null,
                'unidad_id'    => 2,
                'responsable'  => 5,
                'estado'       => 'atendida',
                'prioridad'    => 'media',
                'emision'      => '2026-02-05',
                'limite'       => '2026-03-31',
                'atencion'     => '2026-03-20',
                'sgd'          => 'SGD-010-2026',
                'origen'       => 'SCI',
                'obs'          => 'Libro de reclamaciones digital habilitado. Código QR instalado en mesa de partes y secretaría.',
                'creado_por'   => 3,
                'created_at'   => '2026-02-05 08:00:00',
            ],
            [
                'titulo'       => 'Actualizar matriz de riesgos del área de Logística',
                'descripcion'  => 'La matriz de riesgos del área de Logística no incluye los riesgos asociados a procesos de contratación directa y emergencias. Requiere actualización inmediata.',
                'tipo'         => 'mejora',
                'actividad_id' => 7,
                'unidad_id'    => 7,
                'responsable'  => 11,
                'estado'       => 'atendida',
                'prioridad'    => 'media',
                'emision'      => '2026-02-18',
                'limite'       => '2026-03-30',
                'atencion'     => '2026-03-25',
                'sgd'          => 'SGD-015-2026',
                'origen'       => 'SCI',
                'obs'          => 'Matriz actualizada e incorporada al plan de gestión de riesgos institucional.',
                'creado_por'   => 2,
                'created_at'   => '2026-02-18 09:00:00',
            ],
            // Marzo 2026
            [
                'titulo'       => 'Subsanar deficiencias en archivo de expedientes de personal',
                'descripcion'  => 'Se detectaron 23 legajos de personal sin documentación completa (contratos, títulos, declaraciones juradas). El 35% de expedientes presenta folios desactualizados.',
                'tipo'         => 'observacion',
                'actividad_id' => null,
                'unidad_id'    => 8,
                'responsable'  => 4,
                'estado'       => 'atendida',
                'prioridad'    => 'alta',
                'emision'      => '2026-03-05',
                'limite'       => '2026-04-30',
                'atencion'     => '2026-04-22',
                'sgd'          => 'SGD-020-2026',
                'origen'       => 'Auditoría',
                'obs'          => '21 de 23 legajos regularizados. 2 casos en trámite con declaración jurada provisional.',
                'creado_por'   => 1,
                'created_at'   => '2026-03-05 08:30:00',
            ],
            [
                'titulo'       => 'Establecer indicadores de calidad para supervisión pedagógica',
                'descripcion'  => 'El área de Gestión Pedagógica no cuenta con indicadores cuantitativos para medir la efectividad de las visitas de supervisión. Se recomienda diseñar ficha estandarizada con criterios medibles.',
                'tipo'         => 'mejora',
                'actividad_id' => 8,
                'unidad_id'    => 3,
                'responsable'  => 7,
                'estado'       => 'en_proceso',
                'prioridad'    => 'media',
                'emision'      => '2026-03-20',
                'limite'       => '2026-06-30',
                'atencion'     => null,
                'sgd'          => 'SGD-025-2026',
                'origen'       => 'SCI',
                'obs'          => 'Ficha en elaboración. Primera versión revisada por equipo pedagógico el 15/05/2026.',
                'creado_por'   => 7,
                'created_at'   => '2026-03-20 09:00:00',
            ],
            // Abril 2026
            [
                'titulo'       => 'Formalizar delegación de facultades mediante acto administrativo',
                'descripcion'  => 'La delegación de funciones al jefe de administración para firma de documentos de trámite interno se realiza verbalmente. Debe formalizarse mediante Resolución Directoral conforme al artículo 72 de la Ley N° 27444.',
                'tipo'         => 'observacion',
                'actividad_id' => null,
                'unidad_id'    => 1,
                'responsable'  => 2,
                'estado'       => 'atendida',
                'prioridad'    => 'alta',
                'emision'      => '2026-04-08',
                'limite'       => '2026-04-30',
                'atencion'     => '2026-04-25',
                'sgd'          => 'SGD-033-2026',
                'origen'       => 'OCI',
                'obs'          => 'Emitida Resolución Directoral N° 142-2026-DRE-UGEL-HCB formalizando delegación.',
                'creado_por'   => 1,
                'created_at'   => '2026-04-08 08:00:00',
            ],
            [
                'titulo'       => 'Implementar control de asistencia biométrico',
                'descripcion'  => 'El sistema actual de control de asistencia mediante registro manual presenta riesgos de error e inconsistencias. Se recomienda implementar sistema biométrico para mayor confiabilidad.',
                'tipo'         => 'mejora',
                'actividad_id' => 6,
                'unidad_id'    => 8,
                'responsable'  => 4,
                'estado'       => 'en_proceso',
                'prioridad'    => 'media',
                'emision'      => '2026-04-21',
                'limite'       => '2026-07-31',
                'atencion'     => null,
                'sgd'          => 'SGD-038-2026',
                'origen'       => 'SCI',
                'obs'          => 'Cotización recibida de 3 proveedores. Expediente de contratación en preparación.',
                'creado_por'   => 4,
                'created_at'   => '2026-04-21 10:00:00',
            ],
            // Mayo 2026
            [
                'titulo'       => 'Actualizar el plan de continuidad operativa ante desastres',
                'descripcion'  => 'El plan de continuidad operativa data del año 2021 y no contempla escenarios de desastres naturales frecuentes en la región (huaycos, lluvias intensas). Requiere actualización urgente.',
                'tipo'         => 'recomendacion',
                'actividad_id' => 2,
                'unidad_id'    => 4,
                'responsable'  => 13,
                'estado'       => 'en_proceso',
                'prioridad'    => 'alta',
                'emision'      => '2026-05-06',
                'limite'       => '2026-06-30',
                'atencion'     => null,
                'sgd'          => 'SGD-046-2026',
                'origen'       => 'DRE',
                'obs'          => 'Equipo de trabajo conformado. Borrador del plan en revisión por área de Asesoría Jurídica.',
                'creado_por'   => 2,
                'created_at'   => '2026-05-06 08:00:00',
            ],
            [
                'titulo'       => 'Regularizar actas de acuerdo sin firmar del Comité de SCI',
                'descripcion'  => 'Se identificaron 4 actas del Comité de SCI correspondientes a reuniones de marzo y abril 2026 que no han sido firmadas por todos los miembros. Riesgo de validez de acuerdos.',
                'tipo'         => 'observacion',
                'actividad_id' => null,
                'unidad_id'    => 1,
                'responsable'  => 2,
                'estado'       => 'atendida',
                'prioridad'    => 'media',
                'emision'      => '2026-05-15',
                'limite'       => '2026-05-31',
                'atencion'     => '2026-05-28',
                'sgd'          => 'SGD-051-2026',
                'origen'       => 'Autocontrol',
                'obs'          => '4 actas regularizadas y archivadas. Se dispuso plazo máximo de 5 días para firma de actas futuras.',
                'creado_por'   => 2,
                'created_at'   => '2026-05-15 09:30:00',
            ],
            // Junio 2026
            [
                'titulo'       => 'Mejorar señalización de zonas de seguridad en instalaciones',
                'descripcion'  => 'Inspección de defensa civil identificó señalética de seguridad desactualizada en piso 2. Rutas de evacuación, extintores y zonas seguras requieren nueva señalización conforme a NTP 399.010-1.',
                'tipo'         => 'observacion',
                'actividad_id' => null,
                'unidad_id'    => 7,
                'responsable'  => 11,
                'estado'       => 'pendiente',
                'prioridad'    => 'alta',
                'emision'      => '2026-06-02',
                'limite'       => '2026-06-30',
                'atencion'     => null,
                'sgd'          => 'SGD-059-2026',
                'origen'       => 'Auditoría',
                'obs'          => 'Requerimiento de materiales presentado a Logística el 04/06/2026.',
                'creado_por'   => 1,
                'created_at'   => '2026-06-02 08:00:00',
            ],
            [
                'titulo'       => 'Establecer política de seguridad de información institucional',
                'descripcion'  => 'La UGEL no cuenta con política formal de seguridad de información. Los accesos a sistemas críticos (SIAF, SIGA) no tienen procedimiento de revocación al cese del trabajador.',
                'tipo'         => 'recomendacion',
                'actividad_id' => null,
                'unidad_id'    => 2,
                'responsable'  => 3,
                'estado'       => 'pendiente',
                'prioridad'    => 'alta',
                'emision'      => '2026-06-05',
                'limite'       => '2026-07-31',
                'atencion'     => null,
                'sgd'          => 'SGD-062-2026',
                'origen'       => 'OCI',
                'obs'          => null,
                'creado_por'   => 1,
                'created_at'   => '2026-06-05 09:00:00',
            ],
            [
                'titulo'       => 'Estandarizar formato de informes de gestión por unidad',
                'descripcion'  => 'Los informes de gestión mensuales presentados por cada unidad orgánica no tienen formato uniforme, dificultando su consolidación y análisis comparativo. Se recomienda diseñar plantilla estándar.',
                'tipo'         => 'mejora',
                'actividad_id' => 3,
                'unidad_id'    => 4,
                'responsable'  => 13,
                'estado'       => 'pendiente',
                'prioridad'    => 'baja',
                'emision'      => '2026-06-07',
                'limite'       => '2026-08-31',
                'atencion'     => null,
                'sgd'          => null,
                'origen'       => 'Autocontrol',
                'obs'          => null,
                'creado_por'   => 13,
                'created_at'   => '2026-06-07 11:00:00',
            ],
        ];

        foreach ($recomendaciones as $r) {
            DB::table('recomendaciones')->insert([
                'titulo'             => $r['titulo'],
                'descripcion'        => $r['descripcion'],
                'tipo'               => $r['tipo'],
                'actividad_id'       => $r['actividad_id'],
                'unidad_organica_id' => $r['unidad_id'],
                'responsable_id'     => $r['responsable'],
                'estado'             => $r['estado'],
                'prioridad'          => $r['prioridad'],
                'fecha_emision'      => $r['emision'],
                'fecha_limite'       => $r['limite'],
                'fecha_atencion'     => $r['atencion'],
                'numero_sgd'         => $r['sgd'] ?? null,
                'origen'             => $r['origen'],
                'observaciones'      => $r['obs'] ?? null,
                'creado_por'         => $r['creado_por'],
                'created_at'         => $r['created_at'],
                'updated_at'         => $r['created_at'],
                'deleted_at'         => null,
            ]);
        }

        $this->command->info('✅ Recomendaciones: ' . count($recomendaciones) . ' registros insertados.');
    }
}
