<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BuenasPracticasRecomendacionesSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedBuenasPracticas();
        $this->seedRecomendaciones();
    }

    private function seedBuenasPracticas(): void
    {
        $practicas = [
            // Enero 2026
            [
                'titulo'      => 'Digitalización del archivo documentario institucional',
                'descripcion' => 'Digitalización y organización del acervo documentario de la UGEL Huacaybamba mediante sistema de gestión documental, reduciendo el tiempo de búsqueda de expedientes en un 70% y facilitando el acceso a docentes de zonas rurales que no pueden trasladarse a la sede.',
                'categoria'   => 'innovacion',
                'unidad_id'   => 2,
                'responsable' => 3,
                'estado'      => 'completada',
                'avance'      => 100,
                'inicio'      => '2026-01-06',
                'termino'     => '2026-02-28',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-001-2026',
                'evidencias'  => 'Acta de implementación, manual de usuario, registro de capacitación al personal administrativo.',
                'creado_por'  => 1,
                'created_at'  => '2026-01-06 08:00:00',
            ],
            [
                'titulo'      => 'Protocolo de atención preferente a docentes de zonas rurales',
                'descripcion' => 'Implementación de protocolo de atención prioritaria para docentes provenientes de los distritos de Pinra, Canchabamba y Cochabamba, que deben recorrer largas distancias para realizar trámites. Incluye atención sin cita y atención integral en una sola visita.',
                'categoria'   => 'gestion',
                'unidad_id'   => 2,
                'responsable' => 5,
                'estado'      => 'completada',
                'avance'      => 100,
                'inicio'      => '2026-01-12',
                'termino'     => '2026-03-15',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-002-2026',
                'evidencias'  => 'Directiva interna aprobada, registro de docentes atendidos por distrito, encuesta de satisfacción con 91% de aprobación.',
                'creado_por'  => 1,
                'created_at'  => '2026-01-12 09:30:00',
            ],
            // Febrero 2026
            [
                'titulo'      => 'Programa de fortalecimiento de capacidades en Control Interno',
                'descripcion' => 'Programa de capacitación continua al personal administrativo en materia de Sistema de Control Interno, con talleres bimestrales en la sede de la UGEL Huacaybamba y módulos virtuales para personal de sedes remotas.',
                'categoria'   => 'integridad',
                'unidad_id'   => 1,
                'responsable' => 2,
                'estado'      => 'completada',
                'avance'      => 100,
                'inicio'      => '2026-02-03',
                'termino'     => '2026-04-30',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-008-2026',
                'evidencias'  => 'Listas de asistencia a talleres (87 participantes), evaluaciones aplicadas, certificados emitidos por la DRE Huánuco.',
                'creado_por'  => 2,
                'created_at'  => '2026-02-03 08:00:00',
            ],
            [
                'titulo'      => 'Portal de transparencia actualizado mensualmente',
                'descripcion' => 'Actualización mensual y oportuna del portal de transparencia de la UGEL Huacaybamba (www.ugelhuacaybamba.edu.pe) con información presupuestal, contratos, personal y actos administrativos conforme a la Ley N° 27806.',
                'categoria'   => 'transparencia',
                'unidad_id'   => 1,
                'responsable' => 4,
                'estado'      => 'en_implementacion',
                'avance'      => 85,
                'inicio'      => '2026-02-10',
                'termino'     => '2026-12-31',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-012-2026',
                'evidencias'  => 'Capturas mensuales del portal, cronograma de actualización cumplido en 5 de 6 meses, constancia de publicación en gob.pe/ugelhuacaybamba.',
                'creado_por'  => 4,
                'created_at'  => '2026-02-10 10:00:00',
            ],
            // Marzo 2026
            [
                'titulo'      => 'Simplificación del proceso de viáticos para comisiones a zonas rurales',
                'descripcion' => 'Estandarización y simplificación del proceso de solicitud, aprobación y rendición de viáticos para comisiones de servicio a los distritos de Canchabamba y Pinra, reduciendo el tiempo de procesamiento de 5 a 2 días hábiles y eliminando observaciones recurrentes.',
                'categoria'   => 'gestion',
                'unidad_id'   => 9,
                'responsable' => 9,
                'estado'      => 'completada',
                'avance'      => 100,
                'inicio'      => '2026-03-02',
                'termino'     => '2026-04-15',
                'impacto'     => 'medio',
                'sgd'         => 'SGD-018-2026',
                'evidencias'  => 'Nuevo flujograma aprobado mediante memorándum circular, directiva interna de viáticos, registro comparativo de tiempos antes/después.',
                'creado_por'  => 9,
                'created_at'  => '2026-03-02 08:30:00',
            ],
            [
                'titulo'      => 'Plan de gestión de riesgos de corrupción de la UGEL Huacaybamba',
                'descripcion' => 'Elaboración e implementación del plan de gestión de riesgos de corrupción identificando 12 procesos críticos de la UGEL Huacaybamba, con énfasis en adquisiciones para mantenimiento de locales escolares rurales y contratación de personal docente.',
                'categoria'   => 'integridad',
                'unidad_id'   => 5,
                'responsable' => 6,
                'estado'      => 'completada',
                'avance'      => 100,
                'inicio'      => '2026-03-09',
                'termino'     => '2026-05-30',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-021-2026',
                'evidencias'  => 'Matriz de riesgos aprobada (RD N° 142-2026-UGEL-HCB), plan de gestión, actas de socialización con jefes de unidad.',
                'creado_por'  => 6,
                'created_at'  => '2026-03-09 09:00:00',
            ],
            // Abril 2026
            [
                'titulo'      => 'Banco de recursos pedagógicos para docentes de IIEE rurales',
                'descripcion' => 'Creación de repositorio digital de materiales educativos contextualizados para instituciones educativas unidocentes y multigrado de los 4 distritos de la provincia de Huacaybamba, con énfasis en interculturalidad y lengua quechua.',
                'categoria'   => 'innovacion',
                'unidad_id'   => 3,
                'responsable' => 7,
                'estado'      => 'en_implementacion',
                'avance'      => 70,
                'inicio'      => '2026-04-06',
                'termino'     => '2026-07-31',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-031-2026',
                'evidencias'  => 'Plataforma digital habilitada, 45 materiales cargados para niveles inicial/primaria/secundaria, 98 docentes registrados.',
                'creado_por'  => 7,
                'created_at'  => '2026-04-06 08:00:00',
            ],
            [
                'titulo'      => 'Mesa de partes virtual para trámites de docentes',
                'descripcion' => 'Habilitación de mesa de partes virtual en el portal de la UGEL Huacaybamba, permitiendo el ingreso de documentos en línea a docentes y ciudadanos de los 4 distritos sin necesidad de desplazarse a la sede ubicada en la capital provincial.',
                'categoria'   => 'transparencia',
                'unidad_id'   => 2,
                'responsable' => 8,
                'estado'      => 'en_implementacion',
                'avance'      => 60,
                'inicio'      => '2026-04-13',
                'termino'     => '2026-08-31',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-035-2026',
                'evidencias'  => 'Mesa de partes virtual operativa en www.ugelhuacaybamba.edu.pe, manual de usuario publicado, 97 trámites recibidos en línea.',
                'creado_por'  => 8,
                'created_at'  => '2026-04-13 09:30:00',
            ],
            // Mayo 2026
            [
                'titulo'      => 'Acompañamiento pedagógico en matemáticas para IIEE con bajo rendimiento en ECE',
                'descripcion' => 'Implementación de programa de acompañamiento docente especializado en matemáticas para las 12 instituciones educativas con menor rendimiento en la Evaluación Censal de Estudiantes (ECE 2025), con visitas quincenales y sesiones demostrativas.',
                'categoria'   => 'gestion',
                'unidad_id'   => 3,
                'responsable' => 10,
                'estado'      => 'en_implementacion',
                'avance'      => 55,
                'inicio'      => '2026-05-04',
                'termino'     => '2026-11-30',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-045-2026',
                'evidencias'  => '12 IIEE focalizadas (8 de Huacaybamba, 3 de Cochabamba, 1 de Canchabamba), 24 visitas realizadas, informes de acompañamiento.',
                'creado_por'  => 10,
                'created_at'  => '2026-05-04 08:00:00',
            ],
            [
                'titulo'      => 'Inventario patrimonial con código de barras de la UGEL Huacaybamba',
                'descripcion' => 'Modernización del control patrimonial mediante etiquetado con código de barras de todos los bienes institucionales de la UGEL Huacaybamba y sistema de escaneo para registros rápidos en el SIGA-MEF.',
                'categoria'   => 'gestion',
                'unidad_id'   => 7,
                'responsable' => 11,
                'estado'      => 'en_implementacion',
                'avance'      => 45,
                'inicio'      => '2026-05-11',
                'termino'     => '2026-09-30',
                'impacto'     => 'medio',
                'sgd'         => 'SGD-052-2026',
                'evidencias'  => '340 bienes etiquetados de 756 totales registrados en el SIGA, base de datos patrimonial actualizada.',
                'creado_por'  => 11,
                'created_at'  => '2026-05-11 09:00:00',
            ],
            // Junio 2026
            [
                'titulo'      => 'Protocolo de atención a denuncias ciudadanas en la UGEL',
                'descripcion' => 'Diseño e implementación de protocolo estandarizado para la recepción, registro, derivación y seguimiento de denuncias de ciudadanos y docentes, garantizando respuesta formal en máximo 15 días hábiles conforme a la Ley N° 27444.',
                'categoria'   => 'transparencia',
                'unidad_id'   => 5,
                'responsable' => 12,
                'estado'      => 'en_implementacion',
                'avance'      => 40,
                'inicio'      => '2026-06-01',
                'termino'     => '2026-09-30',
                'impacto'     => 'medio',
                'sgd'         => 'SGD-058-2026',
                'evidencias'  => 'Protocolo aprobado mediante Resolución Directoral, formato de registro implementado en mesa de partes.',
                'creado_por'  => 12,
                'created_at'  => '2026-06-01 08:00:00',
            ],
            [
                'titulo'      => 'Comité de Ética e Integridad Institucional de la UGEL Huacaybamba',
                'descripcion' => 'Conformación y activación del Comité de Ética Institucional con sesiones bimestrales, seguimiento a los 10 compromisos del Modelo de Integridad y difusión permanente del Código de Ética entre el personal y la comunidad educativa.',
                'categoria'   => 'integridad',
                'unidad_id'   => 1,
                'responsable' => 2,
                'estado'      => 'pendiente',
                'avance'      => 15,
                'inicio'      => '2026-06-09',
                'termino'     => '2026-12-31',
                'impacto'     => 'medio',
                'sgd'         => 'SGD-063-2026',
                'evidencias'  => null,
                'creado_por'  => 1,
                'created_at'  => '2026-06-09 09:00:00',
            ],
            [
                'titulo'      => 'Sistema de indicadores de gestión por unidad orgánica',
                'descripcion' => 'Diseño e implementación de tablero de indicadores de desempeño por unidad orgánica de la UGEL Huacaybamba, con metas mensuales y reportes automáticos para la Dirección y la DRE Huánuco.',
                'categoria'   => 'gestion',
                'unidad_id'   => 4,
                'responsable' => 13,
                'estado'      => 'pendiente',
                'avance'      => 10,
                'inicio'      => '2026-06-02',
                'termino'     => '2026-10-31',
                'impacto'     => 'alto',
                'sgd'         => 'SGD-060-2026',
                'evidencias'  => null,
                'creado_por'  => 13,
                'created_at'  => '2026-06-02 08:30:00',
            ],
            [
                'titulo'      => 'Presupuesto participativo con la comunidad educativa provincial',
                'descripcion' => 'Programa de involucramiento de la comunidad educativa de la provincia de Huacaybamba en la priorización de necesidades de infraestructura escolar y seguimiento de inversiones del MINEDU en los 4 distritos.',
                'categoria'   => 'participacion',
                'unidad_id'   => 4,
                'responsable' => 5,
                'estado'      => 'pendiente',
                'avance'      => 5,
                'inicio'      => '2026-06-07',
                'termino'     => '2026-11-30',
                'impacto'     => 'medio',
                'sgd'         => null,
                'evidencias'  => null,
                'creado_por'  => 5,
                'created_at'  => '2026-06-07 10:00:00',
            ],
        ];

        foreach ($practicas as $idx => $p) {
            // Alternar módulo: impares=sci, pares=integridad para variedad
            $modulo = ($idx % 3 === 2) ? 'integridad' : 'sci';
            DB::table('buenas_practicas')->insert([
                'titulo'             => $p['titulo'],
                'descripcion'        => $p['descripcion'],
                'categoria'          => $p['categoria'],
                'modulo'             => $p['modulo'] ?? $modulo,
                'unidad_organica_id' => $p['unidad_id'],
                'responsable_id'     => $p['responsable'],
                'estado'             => $p['estado'],
                'avance'             => $p['avance'],
                'fecha_inicio'       => $p['inicio'],
                'fecha_termino'      => $p['termino'],
                'numero_sgd'         => $p['sgd'] ?? null,
                'impacto'            => $p['impacto'],
                'evidencias'         => $p['evidencias'] ?? null,
                'observaciones'      => null,
                'creado_por'         => $p['creado_por'],
                'created_at'         => $p['created_at'],
                'updated_at'         => $p['created_at'],
                'deleted_at'         => null,
            ]);
        }

        // Proyectos del CONCURSO — flujo dos niveles: UGEL → Externo (MINEDU/DRE)
        $now = now()->toDateTimeString();
        $proyectosConcurso = [
            // NIVEL 0: Presentados (esperan recepción SCI)
            ['titulo'=>'App móvil de seguimiento de trámites docentes','descripcion'=>'Propongo crear una app móvil para que docentes rurales consulten el estado de sus trámites sin necesidad de viajar a la UGEL sede. Incluye notificaciones push y módulo de consulta de boletas.','categoria'=>'innovacion','modulo'=>'sci','unidad_id'=>2,'propuesto_por'=>3,'estado'=>'presentado','evidencias'=>'Encuesta a 45 docentes de Pinra (alta demanda). Prototipo en Figma adjunto.','expediente'=>null,'recepcion'=>null,'puntaje'=>null,'obs'=>null,'nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-06-08 09:15:00'],
            ['titulo'=>'Código de conducta digital para el personal administrativo','descripcion'=>'Elaborar código de conducta para uso ético de herramientas digitales y redes sociales institucionales, alineado al Modelo de Integridad de la CGR.','categoria'=>'integridad','modulo'=>'integridad','unidad_id'=>1,'propuesto_por'=>4,'estado'=>'presentado','evidencias'=>'Normativa CGR sobre modelo de integridad. Experiencias de otras UGEL de Huánuco.','expediente'=>null,'recepcion'=>null,'puntaje'=>null,'obs'=>null,'nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-06-09 10:00:00'],
            // NIVEL 1a: Recepcionado (SCI confirmó — comisión pendiente de evaluar)
            ['titulo'=>'Programa semestral de reconocimiento al personal','descripcion'=>'Crear programa de reconocimiento público al personal administrativo que cumpla metas de gestión, como incentivo no económico que fortalezca la cultura institucional.','categoria'=>'gestion','modulo'=>'sci','unidad_id'=>null,'propuesto_por'=>5,'estado'=>'recepcionado','evidencias'=>'Benchmarking de 3 UGEL que aplican reconocimientos similares.','expediente'=>'EXP-001-2026','recepcion'=>'2026-06-05','puntaje'=>null,'obs'=>null,'nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-06-03 11:30:00'],
            // NIVEL 1b: Elegible (admitido al concurso interno UGEL)
            ['titulo'=>'Sistema de alertas tempranas para docentes en riesgo de abandono','descripcion'=>'Sistema automatizado que detecta patrones de inasistencia y bajo rendimiento en docentes para intervención oportuna del área de personal, reduciendo la deserción laboral.','categoria'=>'gestion','modulo'=>'sci','unidad_id'=>1,'propuesto_por'=>3,'estado'=>'elegible','evidencias'=>'Datos estadísticos de asistencia 2024-2025. Propuesta técnica con wireframes.','expediente'=>'EXP-002-2026','recepcion'=>'2026-05-20','puntaje'=>85,'obs'=>'Proyecto con alto impacto en la gestión del capital humano. La comisión valora la propuesta técnica detallada y la viabilidad de implementación.','nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-05-15 08:00:00'],
            ['titulo'=>'Portal de transparencia interactivo para la comunidad educativa','descripcion'=>'Rediseño del portal de transparencia para hacerlo accesible e interactivo, con infografías, datos abiertos y un chatbot de consultas, alineado al Modelo de Integridad.','categoria'=>'transparencia','modulo'=>'integridad','unidad_id'=>2,'propuesto_por'=>4,'estado'=>'elegible','evidencias'=>'Comparativo de portales de transparencia UGEL a nivel nacional. Maqueta HTML adjunta.','expediente'=>'EXP-003-2026','recepcion'=>'2026-05-22','puntaje'=>78,'obs'=>'Iniciativa alineada al pilar de transparencia del Modelo de Integridad. La comisión reconoce el enfoque en accesibilidad ciudadana.','nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-05-18 09:00:00'],
            // NIVEL 1c: Ganador UGEL → va a concurso externo DRE Huánuco
            ['titulo'=>'Modelo de gestión documental cero papel en la UGEL Huacaybamba','descripcion'=>'Implementación integral de gestión documental electrónica eliminando el uso de papel en todos los procesos internos, con firma digital, flujos de aprobación automatizados y archivo digital centralizado.','categoria'=>'innovacion','modulo'=>'sci','unidad_id'=>1,'propuesto_por'=>5,'estado'=>'ganador_ugel','evidencias'=>'Piloto exitoso en área de personal (3 meses). Ahorro estimado S/. 8,400 anuales en papel e impresión.','expediente'=>'EXP-004-2026','recepcion'=>'2026-04-10','puntaje'=>96,'obs'=>'¡Felicitaciones! Tu proyecto fue seleccionado por unanimidad para representar a la UGEL Huacaybamba. Puntaje: 96/100.','nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-04-05 07:30:00'],
            // NIVEL 2a: Participante externo DRE Huánuco (en curso)
            ['titulo'=>'Plataforma de gestión de riesgos de control interno','descripcion'=>'Plataforma web para identificar, registrar y monitorear riesgos del Sistema de Control Interno conforme a la Guía para la Gestión de Riesgos de la CGR, con alertas automáticas y reportes trimestrales.','categoria'=>'gestion','modulo'=>'sci','unidad_id'=>1,'propuesto_por'=>3,'estado'=>'participante_externo','evidencias'=>'Mapeo de riesgos 2025, Guía CGR, experiencias de otras UGEL en Ancash y Huánuco.','expediente'=>'EXP-005-2026','recepcion'=>'2026-03-15','puntaje'=>91,'obs'=>'Proyecto seleccionado para representar a la UGEL en la DRE Huánuco. Fecha del concurso: 20/06/2026.','nivel_ext'=>'dre','fecha_ext'=>'2026-06-20','resultado_ext'=>null,'created_at'=>'2026-03-10 08:00:00'],
            // NIVEL 2b: Ganador externo MINEDU
            ['titulo'=>'Programa de integridad escolar: formando líderes éticos','descripcion'=>'Programa de formación en valores y ética pública dirigido a estudiantes de secundaria de las II.EE. de la UGEL Huacaybamba, articulado al Modelo de Integridad y con participación de padres de familia.','categoria'=>'integridad','modulo'=>'integridad','unidad_id'=>2,'propuesto_por'=>4,'estado'=>'ganador_externo','evidencias'=>'Piloto en 3 IE (280 estudiantes). Evaluación pre/post con mejora del 34% en indicadores de integridad.','expediente'=>'EXP-006-2026','recepcion'=>'2026-02-20','puntaje'=>98,'obs'=>'¡FELICITACIONES! Ganador del Concurso Nacional de Buenas Prácticas MINEDU 2026. Logro histórico para la UGEL Huacaybamba.','nivel_ext'=>'minedu','fecha_ext'=>'2026-05-15','resultado_ext'=>'1er lugar — Concurso Nacional de Buenas Prácticas en Integridad MINEDU 2026. Puntaje: 98/100.','created_at'=>'2026-02-15 08:00:00'],
            // No elegible
            ['titulo'=>'Rediseño del uniforme institucional del personal','descripcion'=>'Propuesta para unificar la imagen institucional del personal administrativo con uniforme estándar que incluya colores corporativos de la UGEL.','categoria'=>'gestion','modulo'=>'sci','unidad_id'=>null,'propuesto_por'=>3,'estado'=>'no_elegible','evidencias'=>null,'expediente'=>'EXP-007-2026','recepcion'=>'2026-05-01','puntaje'=>null,'obs'=>'La propuesta no cumple con los criterios de innovación en gestión pública requeridos para el concurso. Se sugiere reformular el proyecto enfocándose en mejoras de proceso.','nivel_ext'=>null,'fecha_ext'=>null,'resultado_ext'=>null,'created_at'=>'2026-04-28 10:00:00'],
        ];

        foreach ($proyectosConcurso as $p) {
            DB::table('buenas_practicas')->insert([
                'titulo'                 => $p['titulo'],
                'descripcion'            => $p['descripcion'],
                'categoria'              => $p['categoria'],
                'modulo'                 => $p['modulo'],
                'unidad_organica_id'     => $p['unidad_id'],
                'responsable_id'         => null,
                'estado'                 => $p['estado'],
                'avance'                 => 0,
                'fecha_inicio'           => null,
                'fecha_termino'          => null,
                'numero_sgd'             => null,
                'numero_expediente'      => $p['expediente'],
                'fecha_recepcion'        => $p['recepcion'],
                'impacto'                => null,
                'evidencias'             => $p['evidencias'],
                'observaciones'          => null,
                'feedback_sci'           => $p['obs'],
                'puntaje_comision'       => $p['puntaje'],
                'observacion_comision'   => $p['obs'],
                'nivel_externo'          => $p['nivel_ext'],
                'fecha_concurso_externo' => $p['fecha_ext'],
                'resultado_externo'      => $p['resultado_ext'],
                'propuesto_por'          => $p['propuesto_por'],
                'creado_por'             => $p['propuesto_por'],
                'created_at'             => $p['created_at'],
                'updated_at'             => $p['created_at'],
                'deleted_at'             => null,
            ]);
        }

        $this->command->info('✅ Buenas Prácticas UGEL Huacaybamba: ' . count($practicas) . ' prácticas + ' . count($proyectosConcurso) . ' proyectos del concurso insertados.');
    }

    private function seedRecomendaciones(): void
    {
        // Mapear IDs hardcodeados a IDs reales existentes en la BD
        $actIds = DB::table('actividades')->orderBy('id')->pluck('id')->values();
        $a2 = $actIds->get(1);
        $a3 = $actIds->get(2);
        $a4 = $actIds->get(3);
        $a5 = $actIds->get(4);
        $a6 = $actIds->get(5);
        $a7 = $actIds->get(6);
        $a8 = $actIds->get(7);

        $recomendaciones = [
            // Enero 2026
            [
                'titulo'      => 'Actualizar procedimiento de rendición de cuentas de caja chica',
                'descripcion' => 'Se identificó que el procedimiento de rendición de caja chica de la UGEL Huacaybamba no ha sido actualizado desde el año 2022 y no contempla los cambios normativos de la Directiva N° 005-2023-EF/43.01. Se recomienda actualizar el procedimiento en un plazo de 30 días.',
                'tipo'        => 'recomendacion',
                'actividad_id'=> $a4,
                'unidad_id'   => 6,
                'responsable' => 9,
                'estado'      => 'atendida',
                'prioridad'   => 'alta',
                'emision'     => '2026-01-15',
                'limite'      => '2026-02-15',
                'atencion'    => '2026-02-10',
                'sgd'         => 'SGD-004-2026',
                'origen'      => 'OCI',
                'obs'         => 'Procedimiento actualizado mediante Resolución Directoral N° 035-2026-UGEL-HCB. Se capacitó al personal de Tesorería y Contabilidad.',
                'creado_por'  => 1,
                'created_at'  => '2026-01-15 09:00:00',
            ],
            [
                'titulo'      => 'Regularizar contratos de locadores de servicios vencidos',
                'descripcion' => 'Verificación detectó 8 contratos de locación de servicios con vigencia vencida al 31/12/2025 que continuaban prestando servicios en la UGEL Huacaybamba sin renovación formal. Riesgo legal y presupuestal ante eventual auditoría de la CGR.',
                'tipo'        => 'observacion',
                'actividad_id'=> $a5,
                'unidad_id'   => 8,
                'responsable' => 3,
                'estado'      => 'atendida',
                'prioridad'   => 'alta',
                'emision'     => '2026-01-20',
                'limite'      => '2026-01-31',
                'atencion'    => '2026-01-28',
                'sgd'         => 'SGD-006-2026',
                'origen'      => 'Auditoría',
                'obs'         => '8 contratos renovados conforme a la normativa vigente. Se implementó alerta en el calendario institucional para vencimientos futuros con 30 días de anticipación.',
                'creado_por'  => 2,
                'created_at'  => '2026-01-20 10:30:00',
            ],
            // Febrero 2026
            [
                'titulo'      => 'Implementar libro de reclamaciones en formato digital',
                'descripcion' => 'La UGEL Huacaybamba no cuenta con libro de reclamaciones accesible en formato digital conforme al DS N° 042-2011-PCM. Esto limita el acceso a ciudadanos y docentes de zonas rurales alejadas. Se recomienda habilitar formulario web y código QR en mesa de partes.',
                'tipo'        => 'recomendacion',
                'actividad_id'=> null,
                'unidad_id'   => 2,
                'responsable' => 5,
                'estado'      => 'atendida',
                'prioridad'   => 'media',
                'emision'     => '2026-02-05',
                'limite'      => '2026-03-31',
                'atencion'    => '2026-03-20',
                'sgd'         => 'SGD-010-2026',
                'origen'      => 'SCI',
                'obs'         => 'Libro de reclamaciones digital habilitado en www.ugelhuacaybamba.edu.pe. Código QR instalado en mesa de partes y en acceso principal de la sede.',
                'creado_por'  => 3,
                'created_at'  => '2026-02-05 08:00:00',
            ],
            [
                'titulo'      => 'Actualizar la Matriz de Riesgos del Área de Logística',
                'descripcion' => 'La matriz de riesgos del área de Logística de la UGEL Huacaybamba no incluye los riesgos asociados a adquisiciones para mantenimiento de locales escolares en zonas rurales de difícil acceso (Pinra, Canchabamba). Requiere actualización inmediata.',
                'tipo'        => 'mejora',
                'actividad_id'=> $a7,
                'unidad_id'   => 7,
                'responsable' => 11,
                'estado'      => 'atendida',
                'prioridad'   => 'media',
                'emision'     => '2026-02-18',
                'limite'      => '2026-03-30',
                'atencion'    => '2026-03-25',
                'sgd'         => 'SGD-015-2026',
                'origen'      => 'SCI',
                'obs'         => 'Matriz actualizada e incorporada al plan de gestión de riesgos institucional aprobado mediante RD N° 142-2026-UGEL-HCB.',
                'creado_por'  => 2,
                'created_at'  => '2026-02-18 09:00:00',
            ],
            // Marzo 2026
            [
                'titulo'      => 'Subsanar deficiencias en legajos del personal docente',
                'descripcion' => 'Se detectaron 23 legajos de personal docente de la UGEL Huacaybamba sin documentación completa (títulos pedagógicos, declaraciones juradas, contratos vigentes). El 35% de expedientes presenta folios desactualizados, afectando procesos de evaluación docente 2026.',
                'tipo'        => 'observacion',
                'actividad_id'=> null,
                'unidad_id'   => 8,
                'responsable' => 4,
                'estado'      => 'atendida',
                'prioridad'   => 'alta',
                'emision'     => '2026-03-05',
                'limite'      => '2026-04-30',
                'atencion'    => '2026-04-22',
                'sgd'         => 'SGD-020-2026',
                'origen'      => 'Auditoría',
                'obs'         => '21 de 23 legajos regularizados. 2 casos en trámite con declaración jurada provisional. Se notificó a docentes por correo y telefónicamente.',
                'creado_por'  => 1,
                'created_at'  => '2026-03-05 08:30:00',
            ],
            [
                'titulo'      => 'Establecer indicadores de efectividad para supervisión pedagógica en IIEE rurales',
                'descripcion' => 'El Área de Gestión Pedagógica de la UGEL Huacaybamba no cuenta con indicadores cuantitativos para medir la efectividad de las visitas de supervisión en IIEE de los 4 distritos. Se recomienda diseñar ficha estandarizada con criterios medibles y diferenciados para IIEE unidocentes y multigrado.',
                'tipo'        => 'mejora',
                'actividad_id'=> $a8,
                'unidad_id'   => 3,
                'responsable' => 7,
                'estado'      => 'en_proceso',
                'prioridad'   => 'media',
                'emision'     => '2026-03-20',
                'limite'      => '2026-06-30',
                'atencion'    => null,
                'sgd'         => 'SGD-025-2026',
                'origen'      => 'SCI',
                'obs'         => 'Ficha en elaboración. Primera versión revisada por equipo pedagógico el 15/05/2026. Se incorporaron criterios para IIEE unidocentes de Pinra y Canchabamba.',
                'creado_por'  => 7,
                'created_at'  => '2026-03-20 09:00:00',
            ],
            // Abril 2026
            [
                'titulo'      => 'Formalizar delegación de facultades mediante Resolución Directoral',
                'descripcion' => 'La delegación de funciones al Jefe del Área de Gestión Administrativa para firma de documentos de trámite interno se realizaba verbalmente. Debe formalizarse mediante Resolución Directoral conforme al artículo 72 de la Ley N° 27444 — Ley del Procedimiento Administrativo General.',
                'tipo'        => 'observacion',
                'actividad_id'=> null,
                'unidad_id'   => 1,
                'responsable' => 2,
                'estado'      => 'atendida',
                'prioridad'   => 'alta',
                'emision'     => '2026-04-08',
                'limite'      => '2026-04-30',
                'atencion'    => '2026-04-25',
                'sgd'         => 'SGD-033-2026',
                'origen'      => 'OCI',
                'obs'         => 'Emitida Resolución Directoral N° 142-2026-DRE-UGEL-HCB formalizando la delegación de facultades al Jefe del Área de Gestión Administrativa.',
                'creado_por'  => 1,
                'created_at'  => '2026-04-08 08:00:00',
            ],
            [
                'titulo'      => 'Implementar control de asistencia biométrico en la sede',
                'descripcion' => 'El sistema actual de control de asistencia del personal administrativo de la UGEL Huacaybamba mediante registro manual presenta riesgos de error e inconsistencias. Se recomienda implementar sistema biométrico para mayor confiabilidad y trazabilidad.',
                'tipo'        => 'mejora',
                'actividad_id'=> $a6,
                'unidad_id'   => 8,
                'responsable' => 4,
                'estado'      => 'en_proceso',
                'prioridad'   => 'media',
                'emision'     => '2026-04-21',
                'limite'      => '2026-07-31',
                'atencion'    => null,
                'sgd'         => 'SGD-038-2026',
                'origen'      => 'SCI',
                'obs'         => 'Cotización recibida de 3 proveedores de Huánuco. Expediente de contratación en preparación por Logística.',
                'creado_por'  => 4,
                'created_at'  => '2026-04-21 10:00:00',
            ],
            // Mayo 2026
            [
                'titulo'      => 'Actualizar el Plan de Contingencia ante desastres naturales',
                'descripcion' => 'El plan de contingencia de la UGEL Huacaybamba data del año 2021 y no contempla los escenarios de desastres naturales frecuentes en la zona andina: huaycos, deslizamientos, lluvias intensas y bloqueo de vías de acceso a los distritos de Pinra y Canchabamba. Requiere actualización urgente coordinada con INDECI Huánuco.',
                'tipo'        => 'recomendacion',
                'actividad_id'=> $a2,
                'unidad_id'   => 4,
                'responsable' => 13,
                'estado'      => 'en_proceso',
                'prioridad'   => 'alta',
                'emision'     => '2026-05-06',
                'limite'      => '2026-06-30',
                'atencion'    => null,
                'sgd'         => 'SGD-046-2026',
                'origen'      => 'DRE',
                'obs'         => 'Equipo de trabajo conformado con representantes de INDECI Huánuco. Borrador del plan en revisión por Asesoría Jurídica de la UGEL.',
                'creado_por'  => 2,
                'created_at'  => '2026-05-06 08:00:00',
            ],
            [
                'titulo'      => 'Regularizar actas del Comité de Control Interno sin firmar',
                'descripcion' => 'Se identificaron 4 actas del Comité de Control Interno de la UGEL Huacaybamba correspondientes a las sesiones de marzo y abril 2026 que no habían sido firmadas por todos los miembros. Riesgo de cuestionamiento a la validez de los acuerdos adoptados.',
                'tipo'        => 'observacion',
                'actividad_id'=> null,
                'unidad_id'   => 1,
                'responsable' => 2,
                'estado'      => 'atendida',
                'prioridad'   => 'media',
                'emision'     => '2026-05-15',
                'limite'      => '2026-05-31',
                'atencion'    => '2026-05-28',
                'sgd'         => 'SGD-051-2026',
                'origen'      => 'Autocontrol',
                'obs'         => '4 actas regularizadas, firmadas y archivadas. Se dispuso mediante memorándum plazo máximo de 5 días hábiles para firma de actas futuras.',
                'creado_por'  => 2,
                'created_at'  => '2026-05-15 09:30:00',
            ],
            // Junio 2026
            [
                'titulo'      => 'Mejorar señalización de seguridad en la sede institucional',
                'descripcion' => 'Inspección de Defensa Civil identificó señalética de seguridad desactualizada en el segundo piso de la sede de la UGEL Huacaybamba (Av. 28 de Julio N° 502-504). Rutas de evacuación, extintores y zonas seguras requieren nueva señalización conforme a NTP 399.010-1.',
                'tipo'        => 'observacion',
                'actividad_id'=> null,
                'unidad_id'   => 7,
                'responsable' => 11,
                'estado'      => 'pendiente',
                'prioridad'   => 'alta',
                'emision'     => '2026-06-02',
                'limite'      => '2026-06-30',
                'atencion'    => null,
                'sgd'         => 'SGD-059-2026',
                'origen'      => 'Auditoría',
                'obs'         => 'Requerimiento de materiales presentado a Logística el 04/06/2026. Cotización de proveedor local en Huacaybamba recibida.',
                'creado_por'  => 1,
                'created_at'  => '2026-06-02 08:00:00',
            ],
            [
                'titulo'      => 'Establecer política de seguridad de información y accesos a sistemas SIAF/SIGA',
                'descripcion' => 'La UGEL Huacaybamba no cuenta con política formal de seguridad de información. Los accesos a sistemas críticos (SIAF, SIGA, NEXUS) no cuentan con procedimiento de revocación inmediata al cese del trabajador, generando riesgo de acceso no autorizado.',
                'tipo'        => 'recomendacion',
                'actividad_id'=> null,
                'unidad_id'   => 2,
                'responsable' => 3,
                'estado'      => 'pendiente',
                'prioridad'   => 'alta',
                'emision'     => '2026-06-05',
                'limite'      => '2026-07-31',
                'atencion'    => null,
                'sgd'         => 'SGD-062-2026',
                'origen'      => 'OCI',
                'obs'         => null,
                'creado_por'  => 1,
                'created_at'  => '2026-06-05 09:00:00',
            ],
            [
                'titulo'      => 'Estandarizar formato de informes de gestión mensual por unidad',
                'descripcion' => 'Los informes de gestión mensual presentados por cada unidad orgánica de la UGEL Huacaybamba no tienen formato uniforme, dificultando su consolidación y análisis comparativo por la Dirección. Se recomienda diseñar plantilla estándar alineada a los indicadores del PACI.',
                'tipo'        => 'mejora',
                'actividad_id'=> $a3,
                'unidad_id'   => 4,
                'responsable' => 13,
                'estado'      => 'pendiente',
                'prioridad'   => 'baja',
                'emision'     => '2026-06-07',
                'limite'      => '2026-08-31',
                'atencion'    => null,
                'sgd'         => null,
                'origen'      => 'Autocontrol',
                'obs'         => null,
                'creado_por'  => 13,
                'created_at'  => '2026-06-07 11:00:00',
            ],
        ];

        foreach ($recomendaciones as $r) {
            DB::table('recomendaciones')->insert([
                'titulo'             => $r['titulo'],
                'descripcion'        => $r['descripcion'],
                'tipo'               => $r['tipo'],
                'actividad_id'       => $r['actividad_id'],
                'unidad_organica_id' => $r['unidad_id'],
                'responsable_id'     => $r['responsable'],
                'estado'             => $r['estado'],
                'prioridad'          => $r['prioridad'],
                'fecha_emision'      => $r['emision'],
                'fecha_limite'       => $r['limite'],
                'fecha_atencion'     => $r['atencion'],
                'numero_sgd'         => $r['sgd'] ?? null,
                'origen'             => $r['origen'],
                'observaciones'      => $r['obs'] ?? null,
                'creado_por'         => $r['creado_por'],
                'created_at'         => $r['created_at'],
                'updated_at'         => $r['created_at'],
                'deleted_at'         => null,
            ]);
        }

        $this->command->info('✅ Recomendaciones UGEL Huacaybamba: ' . count($recomendaciones) . ' registros insertados.');
    }
}
