<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Normativa;
use Carbon\Carbon;

class NormativasSeeder extends Seeder
{
    public function run(): void
    {
        Normativa::truncate();

        $normativas = [

            // ══════════════════════════════════════════════════════
            // MÓDULO: GENERAL — Leyes y decretos nacionales
            // ══════════════════════════════════════════════════════
            [
                'nombre'          => 'Ley N° 27785 — Ley Orgánica del Sistema Nacional de Control y de la Contraloría General de la República',
                'codigo'          => 'LEY-27785',
                'descripcion'     => 'Establece las normas que regulan el ámbito, organización, atribuciones y funcionamiento del Sistema Nacional de Control y de la Contraloría General de la República como ente técnico rector de dicho sistema.',
                'tipo'            => 'ley',
                'alcance'         => 'nacional',
                'modulo'          => 'sci',
                'link_externo'    => 'https://www.gob.pe/institucion/contraloria/normas-legales/1625-27785',
                'fecha_emision'   => '2002-07-23',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Congreso de la República',
                'orden'           => 1,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Ley N° 28716 — Ley de Control Interno de las Entidades del Estado',
                'codigo'          => 'LEY-28716',
                'descripcion'     => 'Tiene por objeto establecer las normas para regular la elaboración, aprobación, implantación, funcionamiento, perfeccionamiento y evaluación del control interno en las entidades del Estado, con el propósito de cautelar y fortalecer los sistemas administrativos y operativos con acciones y actividades de control previo, simultáneo y posterior.',
                'tipo'            => 'ley',
                'alcance'         => 'nacional',
                'modulo'          => 'sci',
                'link_externo'    => 'https://www.gob.pe/institucion/contraloria/normas-legales/1626-28716',
                'fecha_emision'   => '2006-04-18',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Congreso de la República',
                'orden'           => 2,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Decreto Supremo N° 004-2019-JUS — Texto Único Ordenado de la Ley N° 27444, Ley del Procedimiento Administrativo General',
                'codigo'          => 'DS-004-2019-JUS',
                'descripcion'     => 'Regula el procedimiento administrativo general aplicable a todas las entidades de la Administración Pública, estableciendo los derechos de los administrados y los principios que rigen la actuación administrativa.',
                'tipo'            => 'decreto',
                'alcance'         => 'nacional',
                'modulo'          => 'general',
                'link_externo'    => 'https://www.gob.pe/institucion/minjus/normas-legales/279147-004-2019-jus',
                'fecha_emision'   => '2019-01-25',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Ministerio de Justicia y Derechos Humanos',
                'orden'           => 3,
                'creado_por'      => 1,
            ],

            // ══════════════════════════════════════════════════════
            // MÓDULO: SCI — Resoluciones y directivas de control interno
            // ══════════════════════════════════════════════════════
            [
                'nombre'          => 'Resolución de Contraloría N° 320-2006-CG — Normas de Control Interno',
                'codigo'          => 'RC-320-2006-CG',
                'descripcion'     => 'Aprueba las Normas de Control Interno con la finalidad de promover una administración adecuada de los recursos públicos en las entidades del Estado. Las normas establecen las pautas generales orientadas a promover una mejor administración de los recursos públicos y el fortalecimiento de los sistemas de control interno.',
                'tipo'            => 'resolucion',
                'alcance'         => 'nacional',
                'modulo'          => 'sci',
                'link_externo'    => 'https://doc.contraloria.gob.pe/libros/2/pdf/RC_320_2006_CG.pdf',
                'fecha_emision'   => '2006-11-03',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Contraloría General de la República',
                'orden'           => 4,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Resolución de Contraloría N° 004-2017-CG — Guía para la Implementación y Fortalecimiento del SCI',
                'codigo'          => 'RC-004-2017-CG',
                'descripcion'     => 'Aprueba la "Guía para la Implementación y Fortalecimiento del Sistema de Control Interno en las Entidades del Estado", estableciendo tres fases: Planificación, Ejecución y Evaluación.',
                'tipo'            => 'resolucion',
                'alcance'         => 'nacional',
                'modulo'          => 'sci',
                'link_externo'    => 'https://doc.contraloria.gob.pe/libros/2/pdf/RC_004_2017_CG.pdf',
                'tutorial_url'    => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'tutorial_tipo'   => 'youtube',
                'fecha_emision'   => '2017-01-20',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Contraloría General de la República',
                'orden'           => 5,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Directiva N° 006-2019-CG/INTEG — Implementación del Sistema de Control Interno en las Entidades del Estado',
                'codigo'          => 'DIR-006-2019-CG',
                'descripcion'     => 'Establece los plazos, procedimientos y responsabilidades para la implementación del Sistema de Control Interno en las entidades del Estado, incluyendo la metodología de autoevaluación y los instrumentos de medición.',
                'tipo'            => 'directiva',
                'alcance'         => 'nacional',
                'modulo'          => 'sci',
                'link_externo'    => 'https://doc.contraloria.gob.pe/libros/2/pdf/RC_146_2019_CG.pdf',
                'fecha_emision'   => '2019-05-14',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Contraloría General de la República',
                'orden'           => 6,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Manual de Implementación del SCI — UGEL Huacaybamba 2024',
                'codigo'          => 'MAN-SCI-UGEL-2024',
                'descripcion'     => 'Manual interno que establece los procedimientos, responsabilidades y cronograma de actividades para la implementación del Sistema de Control Interno en la UGEL Huacaybamba durante el año 2024, en concordancia con la normativa de la Contraloría General de la República.',
                'tipo'            => 'manual',
                'alcance'         => 'institucional',
                'modulo'          => 'sci',
                'fecha_emision'   => '2024-01-15',
                'fecha_vigencia'  => '2024-12-31',
                'vigente'         => false,
                'entidad_emisora' => 'UGEL Huacaybamba',
                'orden'           => 7,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Manual de Implementación del SCI — UGEL Huacaybamba 2025-2026',
                'codigo'          => 'MAN-SCI-UGEL-2025',
                'descripcion'     => 'Manual actualizado para el bienio 2025-2026 que consolida las lecciones aprendidas del período anterior e incorpora las mejoras identificadas en la autoevaluación del SCI. Incluye matrices de riesgo por unidad orgánica y plan de acción correctiva.',
                'tipo'            => 'manual',
                'alcance'         => 'institucional',
                'modulo'          => 'sci',
                'fecha_emision'   => '2025-01-10',
                'fecha_vigencia'  => '2026-12-31',
                'vigente'         => true,
                'entidad_emisora' => 'UGEL Huacaybamba',
                'orden'           => 8,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Reglamento Interno de Control y Gestión de Riesgos — UGEL Huacaybamba',
                'codigo'          => 'REG-RIESGOS-UGEL-2025',
                'descripcion'     => 'Establece las normas internas para la identificación, evaluación, respuesta y monitoreo de riesgos institucionales en la UGEL Huacaybamba, conforme a los lineamientos del COSO ERM y la normativa de la CGR.',
                'tipo'            => 'reglamento',
                'alcance'         => 'institucional',
                'modulo'          => 'sci',
                'fecha_emision'   => '2025-03-01',
                'fecha_vigencia'  => '2027-02-28',
                'vigente'         => true,
                'entidad_emisora' => 'UGEL Huacaybamba',
                'orden'           => 9,
                'creado_por'      => 1,
            ],

            // ══════════════════════════════════════════════════════
            // MÓDULO: INTEGRIDAD — Modelo de Integridad PCM
            // ══════════════════════════════════════════════════════
            [
                'nombre'          => 'Decreto Supremo N° 042-2018-PCM — Condiciones para la Gestión de Integridad Pública',
                'codigo'          => 'DS-042-2018-PCM',
                'descripcion'     => 'Establece las condiciones para que las entidades de la Administración Pública implementen medidas orientadas a prevenir la corrupción, garantizar la integridad de sus servidores y fortalecer la transparencia institucional.',
                'tipo'            => 'decreto',
                'alcance'         => 'nacional',
                'modulo'          => 'integridad',
                'link_externo'    => 'https://www.gob.pe/institucion/pcm/normas-legales/170432-042-2018-pcm',
                'fecha_emision'   => '2018-04-26',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Presidencia del Consejo de Ministros',
                'orden'           => 10,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Resolución Ministerial N° 083-2021-PCM — Modelo de Integridad para las Entidades del Sector Público',
                'codigo'          => 'RM-083-2021-PCM',
                'descripcion'     => 'Aprueba el Modelo de Integridad para las Entidades del Sector Público, el cual comprende cinco pilares: Compromiso institucional, Gestión de conflictos de intereses, Transparencia, Rendición de cuentas y Control interno.',
                'tipo'            => 'resolucion',
                'alcance'         => 'nacional',
                'modulo'          => 'integridad',
                'link_externo'    => 'https://www.gob.pe/institucion/pcm/normas-legales/1697682-083-2021-pcm',
                'tutorial_url'    => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
                'tutorial_tipo'   => 'youtube',
                'fecha_emision'   => '2021-04-23',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Presidencia del Consejo de Ministros',
                'orden'           => 11,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Directiva N° 002-2020-PCM/SGP — Implementación del Modelo de Integridad',
                'codigo'          => 'DIR-002-2020-PCM',
                'descripcion'     => 'Regula el proceso de implementación, seguimiento y evaluación del Modelo de Integridad en las entidades de la Administración Pública, estableciendo los plazos, herramientas y responsabilidades de cada actor institucional.',
                'tipo'            => 'directiva',
                'alcance'         => 'nacional',
                'modulo'          => 'integridad',
                'link_externo'    => 'https://www.gob.pe/institucion/pcm/normas-legales/640736-002-2020-pcm-sgp',
                'fecha_emision'   => '2020-07-15',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Presidencia del Consejo de Ministros — SGP',
                'orden'           => 12,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Código de Ética de la Función Pública — Ley N° 27815',
                'codigo'          => 'LEY-27815',
                'descripcion'     => 'Establece los principios, deberes y prohibiciones éticas que rigen para los servidores públicos, así como las sanciones aplicables ante su incumplimiento. Es de aplicación obligatoria para todos los servidores y funcionarios del Estado.',
                'tipo'            => 'ley',
                'alcance'         => 'nacional',
                'modulo'          => 'integridad',
                'link_externo'    => 'https://www.gob.pe/institucion/servir/normas-legales/1169327-27815',
                'fecha_emision'   => '2002-08-13',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Congreso de la República',
                'orden'           => 13,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Plan de Integridad Institucional — UGEL Huacaybamba 2025-2026',
                'codigo'          => 'PII-UGEL-2025',
                'descripcion'     => 'Plan bienal que articula las acciones institucionales para fortalecer la cultura de integridad, prevenir actos de corrupción y promover la transparencia en todos los procesos de la UGEL Huacaybamba. Incluye cronograma de capacitaciones, indicadores de seguimiento y responsables por pilar.',
                'tipo'            => 'directiva',
                'alcance'         => 'institucional',
                'modulo'          => 'integridad',
                'fecha_emision'   => '2025-02-03',
                'fecha_vigencia'  => '2026-12-31',
                'vigente'         => true,
                'entidad_emisora' => 'UGEL Huacaybamba',
                'orden'           => 14,
                'creado_por'      => 1,
            ],

            // ══════════════════════════════════════════════════════
            // MÓDULO: GENERAL — Gestión educativa y administrativa
            // ══════════════════════════════════════════════════════
            [
                'nombre'          => 'Ley N° 28044 — Ley General de Educación',
                'codigo'          => 'LEY-28044',
                'descripcion'     => 'Establece los lineamientos generales de la educación y del Sistema Educativo Peruano, las atribuciones y obligaciones del Estado y los derechos y responsabilidades de las personas y la sociedad en su función educadora.',
                'tipo'            => 'ley',
                'alcance'         => 'nacional',
                'modulo'          => 'general',
                'link_externo'    => 'https://www.gob.pe/institucion/minedu/normas-legales/118378-28044',
                'fecha_emision'   => '2003-07-29',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'Congreso de la República',
                'orden'           => 15,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Resolución Ministerial N° 189-2025-MINEDU — Orientaciones para el Año Escolar 2025',
                'codigo'          => 'RM-189-2025-MINEDU',
                'descripcion'     => 'Establece las disposiciones y orientaciones pedagógicas para el desarrollo del año escolar 2025 en las instituciones educativas de la Educación Básica, incluyendo la calendarización, criterios de evaluación y gestión del tiempo escolar.',
                'tipo'            => 'resolucion',
                'alcance'         => 'nacional',
                'modulo'          => 'general',
                'link_externo'    => 'https://www.gob.pe/minedu',
                'fecha_emision'   => '2025-03-15',
                'fecha_vigencia'  => '2025-12-31',
                'vigente'         => true,
                'entidad_emisora' => 'Ministerio de Educación',
                'orden'           => 16,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Reglamento de Organización y Funciones — UGEL Huacaybamba (ROF)',
                'codigo'          => 'ROF-UGEL-HUACAYBAMBA-2023',
                'descripcion'     => 'Documento de gestión institucional que establece la estructura orgánica, funciones generales y específicas, atribuciones, responsabilidades y relaciones de coordinación de la UGEL Huacaybamba, aprobado mediante Resolución Directoral Regional.',
                'tipo'            => 'reglamento',
                'alcance'         => 'institucional',
                'modulo'          => 'general',
                'fecha_emision'   => '2023-05-20',
                'fecha_vigencia'  => null,
                'vigente'         => true,
                'entidad_emisora' => 'UGEL Huacaybamba',
                'orden'           => 17,
                'creado_por'      => 1,
            ],
            [
                'nombre'          => 'Oficio Circular N° 015-2026-UGEL-HB/DIR — Lineamientos para el Reporte Mensual de Actividades SCI',
                'codigo'          => 'OC-015-2026-UGEL',
                'descripcion'     => 'Establece los lineamientos, formatos y plazos para el reporte mensual de avance de actividades del Sistema de Control Interno por parte de los responsables de cada unidad orgánica de la UGEL Huacaybamba.',
                'tipo'            => 'oficio',
                'alcance'         => 'institucional',
                'modulo'          => 'sci',
                'fecha_emision'   => '2026-01-08',
                'fecha_vigencia'  => '2026-12-31',
                'vigente'         => true,
                'entidad_emisora' => 'Dirección — UGEL Huacaybamba',
                'orden'           => 18,
                'creado_por'      => 1,
            ],
        ];

        foreach ($normativas as $data) {
            Normativa::create($data);
        }

        $this->command->info('✅ NormativasSeeder: ' . count($normativas) . ' normativas creadas correctamente.');
    }
}
