<?php
// Variables del sistema PULSO UGEL
return [
  "creatorName"    => env('APP_NAME', 'PULSO UGEL'),
  "creatorUrl"     => env('APP_URL', 'http://localhost'),
  "templateName"   => env('APP_NAME', 'PULSO UGEL'),
  "templateSuffix" => "Sistema de Control Interno",
  "templateVersion" => "2.1.3",
  "templateFree"   => false,
  "templateDescription" => "Sistema de Monitoreo de Control Interno e Integridad Institucional",
  "templateKeyword" => "control interno, UGEL, integridad, monitoreo, Perú",
  "licenseUrl"     => "",
  "livePreview"    => env('APP_URL', 'http://localhost'),
  "productPage"    => env('APP_URL', 'http://localhost'),
  "support"        => "",
  "moreThemes"     => "",
  "ogTitle"        => env('APP_NAME', 'PULSO UGEL') . " — Sistema de Control Interno",
  "ogImage"        => "",
  "ogType"         => "website",
  "documentation"  => "",
  "generator"      => "",
  "changelog"      => "",
  "repository"     => "",
  "gitRepo"        => "",
  "gitRepoAccess"  => "",
  "githubFreeUrl"  => "",
  "facebookUrl"    => "",
  "twitterUrl"     => "",
  "githubUrl"      => "",
  "dribbbleUrl"    => "",
  "instagramUrl"   => "",
];
